env:
  dev2
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Changeme_123
    url: jdbc:mysql://119.29.199.151:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
server:
  port: 7003
girl:
  name:  xioao
  age: 24
