spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Changeme_123
    url: jdbc:mysql://119.29.199.151:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
  redis:
    host: localhost
    port: 6379

server:
  port: 7006
